### ISSUE TITLE
client cert and ca fields required but not used

### ISSUE THREAD

**Issue by qrkourier** [openziti/fabric#546]
In Ziti release v0.26.11, the edge controller's `web` bind points and the edge router's `ws` transport can be configured to present a third-party server certificate. The errors from Fabric indicate that a CA certificate and client certificate files must be readable. Still, they are not used, and it is often impossible to supply a valid client certificate when the server certificate is from a third party.

### Controller Config

```yaml
web:
  - name: client-management
    bindPoints:
      - interface: 0.0.0.0:8440
        address: ctrl.example.com:8440
    identity:
      server_cert: /etc/letsencrypt/live/example.com/fullchain.pem
      key: /etc/letsencrypt/live/example.com/privkey.pem
      ca: /etc/pki/ca/kentest/certs/ca.pem  # irrelevant and unused
      cert: /etc/pki/ca/kentest/certs/client1.pem  # irrelevant and unused
```

Error if omitted:

```
Dec 05 14:35:42 ip-172-31-28-116 ziti-controller[137909]: panic: error parsing web configuration [web] at index [0]: error parsing identity section: error parsing identity: required configuration value [web.identity.cert] is missing or is b
lank
Dec 05 14:35:42 ip-172-31-28-116 ziti-controller[137909]: goroutine 1 [running]:
Dec 05 14:35:42 ip-172-31-28-116 ziti-controller[137909]: github.com/openziti/fabric/controller.(*Controller).Run(0xc0001fa0f0)
Dec 05 14:35:42 ip-172-31-28-116 ziti-controller[137909]:         github.com/openziti/fabric@v0.21.17/controller/controller.go:257 +0xa74
Dec 05 14:35:42 ip-172-31-28-116 ziti-controller[137909]: github.com/openziti/ziti/ziti-controller/subcmd.run(0x3697540?, {0xc0008927e0, 0x1, 0x3?})
Dec 05 14:35:42 ip-172-31-28-116 ziti-controller[137909]:         github.com/openziti/ziti/ziti-controller/subcmd/run.go:92 +0xac5
Dec 05 14:35:42 ip-172-31-28-116 ziti-controller[137909]: github.com/spf13/cobra.(*Command).execute(0x3697540, {0xc000892780, 0x3, 0x3})
Dec 05 14:35:42 ip-172-31-28-116 ziti-controller[137909]:         github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
Dec 05 14:35:42 ip-172-31-28-116 ziti-controller[137909]: github.com/spf13/cobra.(*Command).ExecuteC(0x3697260)
Dec 05 14:35:42 ip-172-31-28-116 ziti-controller[137909]:         github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
Dec 05 14:35:42 ip-172-31-28-116 ziti-controller[137909]: github.com/spf13/cobra.(*Command).Execute(...)
Dec 05 14:35:42 ip-172-31-28-116 ziti-controller[137909]:         github.com/spf13/cobra@v1.6.1/command.go:968
Dec 05 14:35:42 ip-172-31-28-116 ziti-controller[137909]: github.com/openziti/ziti/ziti-controller/subcmd.Execute()
Dec 05 14:35:42 ip-172-31-28-116 ziti-controller[137909]:         github.com/openziti/ziti/ziti-controller/subcmd/root.go:70 +0x25
Dec 05 14:35:42 ip-172-31-28-116 ziti-controller[137909]: main.main()
Dec 05 14:35:42 ip-172-31-28-116 ziti-controller[137909]:         github.com/openziti/ziti/ziti-controller/main.go:47 +0x17
```

### Router Config

```yaml
transport:
  ws:
    identity:
        server_cert: /etc/letsencrypt/live/example.com/fullchain.pem
        key: /etc/letsencrypt/live/example.com/privkey.pem
        ca: /etc/pki/ca/kentest/certs/ca.pem  # irrelevant and unused
        cert: /etc/pki/ca/kentest/certs/client1.pem  # irrelevant and unused
```

Error if omitted:

```
Dec 05 14:32:26 ip-172-31-28-116 ziti-router[137369]: [52346.040]   FATAL fabric/router.(*Router).startXgressListeners: error listening [edge] (load configuration: could not validate identity section: required configuration value [transport.ws.ca] is missing or is blank)
```

**Comment by qrkourier** [comment]
stale
